### ISSUE TITLE
Improve output formatting

### ISSUE THREAD

**Issue by breadthe** [nunomaduro/collision#100]
As discussed on Twitter, I think it would be useful to display diff results returned by the `php artisan test` command more in line with those from `phpunit`, i.e. improved formatting with line breaks and indentation.

A particular example is the `assertDatabaseHas` helper which produces the following sample output when it fails to locate a record:

<img width="709" alt="2020-03-12-phpunit-assert-database-has" src="https://user-images.githubusercontent.com/17433578/76522180-29c3db80-6434-11ea-976f-3416de9ec0d4.png">

In contrast, `php artisan test` shows:

<img width="1309" alt="2020-03-12-collision-assert-database-has" src="https://user-images.githubusercontent.com/17433578/76522223-3cd6ab80-6434-11ea-91f8-3ce537523059.png">

**Comment by nunomaduro** [comment]
@breadthe Can you try to work in a pull request to fix this?

**Comment by breadthe** [comment]
@nunomaduro Apologies Nuno, I didn't notice your reply.
I'm afraid I can't commit to working on it - I simply don't have the bandwidth right now but if my schedule clears up at some point, I'll circle back to it and try to help.

**Comment by nunomaduro** [comment]
Fell free to contribute with a solution for this.
