### ISSUE TITLE
Tests stop without any information

### ISSUE THREAD

**Issue by apoca** [nunomaduro/collision#101]
Hi @nunomaduro, I have started using your repo `php artisan test`, but I am facing a problem after some while tests stop without any error...

I have around 700 tests. And I am using PHPUnit and it takes roughly Time: 7.57 minutes, Memory: 317.00 MB.

My actual command: `php -d memory_limit=512M vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests`

With your: `PHP artisan test` I got an error:

<img width="841" alt="Screenshot 2020-03-21 at 16 46 27" src="https://user-images.githubusercontent.com/5594091/77231588-ed128580-6b93-11ea-9c9a-61aa899f999c.png">

**Comment by nunomaduro** [comment]
Can you try with an increased memory limit?

**Comment by apoca** [comment]
@nunomaduro something like this: `php -d memory_limit=2000M artisan test` ?

Yes, I did it and stopped.

More info phpunit:

```xml
<phpunit
        backupGlobals="false"
        backupStaticAttributes="false"
        beStrictAboutTestsThatDoNotTestAnything="true"
        beStrictAboutOutputDuringTests="true"
        bootstrap="vendor/autoload.php"
        colors="true"
        convertErrorsToExceptions="true"
        convertNoticesToExceptions="true"
        convertWarningsToExceptions="true"
        failOnRisky="true"
        failOnWarning="true"
        processIsolation="false"
        stopOnError="true"
        stopOnFailure="true"
        verbose="true"
        printerClass="NunoMaduro\Collision\Adapters\Phpunit\Printer">
```

**Comment by nunomaduro** [comment]
You need to give me more info here.

If you filter by that test only, also stops?

**Comment by apoca** [comment]
No. I think that is something about memory leak, but when I execute for example:

`php -d memory_limit=512M vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests`

works as expected. 

<img width="1276" alt="Screenshot 2020-03-21 at 20 54 02" src="https://user-images.githubusercontent.com/5594091/77236433-54413180-6bb6-11ea-81cb-c6d671acc089.png">

**Comment by nunomaduro** [comment]
Can you try to debug this?

**Comment by apoca** [comment]
I have solved that issue. It was a docker caching... After restarting is working locally with memory_limit = -1 in PHP.ini. Thanks @nunomaduro :)
