### ISSUE TITLE
How to use listener version

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/collision#102]
I used to use our own result-printer alongside listener for uber beautiful output.

However, just updated to Laravel 7 and the listener no longer works?  

Is there still a way to use the Collision listener and not as printerClass?

**Comment by nunomaduro** [comment]
You just want the error output with your own result-printer?

**Comment by mikeerickson** [comment]
Yes, that is correct. When it was a listener option the output combined with our printer, it looked better

**Comment by johanvanhelden** [comment]
I would also prefer an error-only listener.

**Comment by nunomaduro** [comment]
Duplicate of https://github.com/nunomaduro/collision/issues/99

**Comment by mikeerickson** [comment]
@nunomaduro Have you considered adding this?
