### ISSUE TITLE
A couple issues with the PHPUnit printer

### ISSUE THREAD

**Issue by m50** [nunomaduro/collision#104]
So there are two main issues I have with the PHPUnit printer:

1. If you pass `--coverage-text` into phpunit, it doesn't give the coverage information.
2. If you `dump()` inside your tests, the last couple lines of the dump get stripped out, because of how you are replacing output in the console.

<details>
  <summary>Images!</summary>

  1.
  ![image](https://user-images.githubusercontent.com/3577147/78071974-f35aeb80-7363-11ea-9050-93fc1ff9b7db.png)

  2.
  ![image](https://user-images.githubusercontent.com/3577147/78071788-b0007d00-7363-11ea-9795-90c20b90c970.png)

</details>

I'll submit a PR for these if I have the time, but I wanted to record these here in case someone else wants to tackle them.

**Comment by nunomaduro** [comment]
That mainly related to the fact that we use symfony's output sections for providing some console animations. And they don't behave well with long outputs.

Honestly, I am using collision for pest, so I am thinking about remove those animations.

**Comment by m50** [comment]
I think doing it the way `--testdox` does it, where it prints them out as they are finished may be a good compromise, instead of replacing the test one by one, then pushing them all up at once.

**Comment by nunomaduro** [comment]
@m50 Agree. Even thought the code may be a little messy, do you think you are able to work on it?

**Comment by m50** [comment]
@nunomaduro  Not this week, but I can start to take a look next week.
