### ISSUE TITLE
Warning about abandoned package

### ISSUE THREAD

**Issue by emilas44** [nunomaduro/collision#111]
After composer update I get a warning about deprecated packages

```
composer update
Loading composer repositories with package information                                                                                                                                                                                                    Updating dependencies (including require-dev)         
Package operations: 1 install, 6 updates, 0 removals
  - Updating league/commonmark (1.3.2 => 1.3.3): Downloading (100%)         
  - Updating psy/psysh (v0.10.2 => v0.10.3): Downloading (100%)         
  - Updating laravel/framework (v6.18.3 => v6.18.6): Downloading (100%)         
  - Updating laravel/tinker (v2.3.0 => v2.4.0): Downloading (100%)         
  - Installing sebastian/code-unit (1.0.0): Downloading (100%)         
  - Updating phpunit/phpunit (9.0.2 => 9.1.1): Downloading (100%)         
  - Updating composer/ca-bundle (1.2.6 => 1.2.7): Downloading (100%)         
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Writing lock file
Generating optimized autoload files
```

**Comment by PHPGuus** [comment]
I'm working on a PR for this

**Comment by PHPGuus** [comment]
Actually, this is an old(er) version of collision that is causing the problem (v3.0.1). @nunomaduro Do you want a PR for 3.0.1 to fix this, or would you rather have laravel upgrade a ^4.x version?

**Comment by nunomaduro** [comment]
Can you check if that problem comes **only** from Collision `3.x`?

**Comment by PHPGuus** [comment]
You're right... It is on 3.0.1, 4.0.x, and 4.1.x.
How to proceed?

**Comment by PHPGuus** [comment]
Do you want a PR against each branch, or what would you like me to do?

**Comment by nunomaduro** [comment]
> Can you check if that problem comes only from Collision 3.x?

This question was about: is laravel/tinker also fixing this problem in their side for the 6.x series? Because they also have issue.

**Comment by emilas44** [comment]
Oh boy, I've wreaked havoc with this, haven't I...

**Comment by PHPGuus** [comment]
It might, but those branches I mentioned rely directly on this package that is abandoned, so I don't really see how laravel/tinker could help with that...

**Comment by PHPGuus** [comment]
PR against each branch?

**Comment by devNoiseConsulting** [comment]
I was able to update Laravel/Tinker to 2.4 on my Laravel 6.x project. Would changing the Laravel dependency to be "^6.0|^7.0" work? Or are there breaking changes that prevent the 4.x version from working with Laravel 6?

**Comment by nunomaduro** [comment]
Sorry, I have no plans on fixed this on the 3.x branch.

**Comment by ZBrettonYe** [comment]
The problem is 4.x branch require `symfony/console": "^5.0`.
My laravel framework is 5.8.x, which require `symfony/console": "^4.2`

The end, I was forced to stay at 3.x branch and watch the warning happen o(╥﹏╥)o
or I update my laravel
