### ISSUE TITLE
Running with stderr causes exception

### ISSUE THREAD

**Issue by dmason30** [nunomaduro/collision#113]
**Description**
Running with the `--stderr` arg causes this below exception: 

```
> vendor/bin/phpunit --stderr

In PrinterContents.php line 56:
                                                                               
  Argument 1 passed to NunoMaduro\Collision\Adapters\Phpunit\Printer::__const  
  ruct() must be an instance of Symfony\Component\Console\Output\ConsoleOutpu  
  t or null, string given, called in /Users/<name>/PhpstormProjects/service  
  s/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 1159   
```
Not sure if you want to do anything about it since I only encountered this after  upgrading to v4 and using the new `Printer` class. I have removed the `--stderr`  argument and it works like a charm  😄 

**Environment**
PHP Version: 7.4
PHPUnit Version: 9.1.1
Package Version: 4.2.0

**Comment by nunomaduro** [comment]
I think the collision printer don't support that issue, feel free to pull request that feature.
