### ISSUE TITLE
No application encryption key has been specified.

### ISSUE THREAD

**Issue by finagin** [nunomaduro/collision#116]
* `v4.2.0` - when run `php artisan test` command crush with `No application encryption key has been specified.`
* `v4.1.3` - when run `php artisan test` command crush with `No application encryption key has been specified.`
* `v4.1.2` - all right

**Comment by nunomaduro** [comment]
Have you generated the key?

**Comment by finagin** [comment]
In the `.env.testing` file that is in git there is a section `APP_KEY=`

```env
APP_KEY=

DB_CONNECTION=sqlite
DB_DATABASE=database/database.sqlite
```

**Comment by nunomaduro** [comment]
That APP_Key needs to have a value.

**Comment by finagin** [comment]
that is, before it was generated by the `test` command, and now I need to keep it in git?
