### ISSUE TITLE
Collision printer class stoping on failure

### ISSUE THREAD

**Issue by Arkanius** [nunomaduro/collision#120]
Hello,

I just bumped my app to **Laravel 7** and started using the **PHPUnit 9**. When I run my tests without the printer class they don't stop at first failure; however, when I try to set the printer class at phpunit.xml they stop at first failure.

Is there any way to configure this?

**With printerClass:**
> printerClass="NunoMaduro\Collision\Adapters\Phpunit\Printer">

![image](https://user-images.githubusercontent.com/6404401/82385500-a1038600-9a08-11ea-8464-ff55a62a6f15.png)

**Without printer class:**
![image](https://user-images.githubusercontent.com/6404401/82385716-1ec79180-9a09-11ea-9057-b81cc6cdc55d.png)

**Comment by nunomaduro** [comment]
On Collision 4 you can't do that.

Try Collision 5 and tell me how it goes.

**Comment by Arkanius** [comment]
Thanks, worked well.

Do you think this deserve a note in the docs? I can handle this if you wish

**Comment by nunomaduro** [comment]
Collision 5 is beta 👍 

Let's wait for the stable release.
