### ISSUE TITLE
Some "lag" on v5-BETA

### ISSUE THREAD

**Issue by robsontenorio** [nunomaduro/collision#121]
After upgrading to v5, just noticed some "lag" between test cases, what increases total time of tests. On previous version total time were very similar.

Without collision (2.5 seconds)

![image](https://user-images.githubusercontent.com/118955/82624868-1498c500-9bba-11ea-8745-95c472952006.png)

With collision (3.93)

![image](https://user-images.githubusercontent.com/118955/82624930-35611a80-9bba-11ea-8892-683358a17a0d.png)

**Comment by nunomaduro** [comment]
Yeah, we have a sleep to make animations a little bit better: https://github.com/nunomaduro/collision/blob/fef86518b5bab6373eb282068bfa4ce25bb723d1/src/Adapters/Phpunit/Style.php#L64.

**Comment by robsontenorio** [comment]
Just noticed this “lag” is bigger with larger phpunit datasets.

**Comment by Christophvh** [comment]
> Yeah, we have a sleep to make animations a little bit better:
> 
> https://github.com/nunomaduro/collision/blob/fef86518b5bab6373eb282068bfa4ce25bb723d1/src/Adapters/Phpunit/Style.php#L64
> 
> .

Would be nice to have at least the option to disable this, slowing down tests on purpose is really annoying. It also costs money. Github actions for example charges based on minutes so this makes developers using your package pay more. We have some projects with 900+ tests I rather run faster than having pretty animations.

**Comment by nunomaduro** [comment]
@AlexMartinFR Are you still working on the `compact` thing?

**Comment by alexmartinfr** [comment]
Yes, but I haven't figured the way to pass a command or a parameter from Pest to Collision yet.

Once we have that it would be easy to remove that `usleep` for this rendering mode.

**Comment by Christophvh** [comment]
if you keep it. There should be a giant warning in the docs to just use PHPUnit for ci-tools like travis/github actions or if you are struggling with speed.

**Comment by Krisell** [comment]
I also noticed this for a Laravel 8 project, and using `phpunit` directly now instead of `php artisan test` to avoid the slow-down.

**Comment by nunomaduro** [comment]
Fixed.
