### ISSUE TITLE
Exception thrown while installing collition 5.0 in laravel 6

### ISSUE THREAD

**Issue by Im-TroN** [nunomaduro/collision#133]
composer require nunomaduro/collision:"^5.0" --dev --update-with-dependencies
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: don't install nunomaduro/collision v5.0.0-BETA4
    - Conclusion: don't install nunomaduro/collision v5.0.0-BETA3
    - Conclusion: don't install nunomaduro/collision v5.0.0-BETA2
    - Conclusion: remove symfony/console v4.4.10
    - Installation request for nunomaduro/collision ^5.0 -> satisfiable by nunomaduro/collision[v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-BETA3, v5.0.0-BETA4].
    - Conclusion: don't install symfony/console v4.4.10
    - nunomaduro/collision v5.0.0-BETA1 requires symfony/console ^5.0 -> satisfiable by symfony/console[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2].
    - Can only install one of: symfony/console[5.0.x-dev, v4.4.10].
    - Can only install one of: symfony/console[5.1.x-dev, v4.4.10].
    - Can only install one of: symfony/console[5.2.x-dev, v4.4.10].
    - Can only install one of: symfony/console[v5.0.0, v4.4.10].
    - Can only install one of: symfony/console[v5.0.0-BETA1, v4.4.10].
    - Can only install one of: symfony/console[v5.0.0-BETA2, v4.4.10].
    - Can only install one of: symfony/console[v5.0.0-RC1, v4.4.10].
    - Can only install one of: symfony/console[v5.0.1, v4.4.10].
    - Can only install one of: symfony/console[v5.0.10, v4.4.10].
    - Can only install one of: symfony/console[v5.0.2, v4.4.10].
    - Can only install one of: symfony/console[v5.0.3, v4.4.10].
    - Can only install one of: symfony/console[v5.0.4, v4.4.10].
    - Can only install one of: symfony/console[v5.0.5, v4.4.10].
    - Can only install one of: symfony/console[v5.0.6, v4.4.10].
    - Can only install one of: symfony/console[v5.0.7, v4.4.10].
    - Can only install one of: symfony/console[v5.0.8, v4.4.10].
    - Can only install one of: symfony/console[v5.0.9, v4.4.10].
    - Can only install one of: symfony/console[v5.1.0, v4.4.10].
    - Can only install one of: symfony/console[v5.1.0-BETA1, v4.4.10].
    - Can only install one of: symfony/console[v5.1.0-RC1, v4.4.10].
    - Can only install one of: symfony/console[v5.1.0-RC2, v4.4.10].
    - Can only install one of: symfony/console[v5.1.1, v4.4.10].
    - Can only install one of: symfony/console[v5.1.2, v4.4.10].
    - Installation request for symfony/console (locked at v4.4.10) -> satisfiable by symfony/console[v4.4.10].

**Comment by nunomaduro** [comment]
Collision is not compatible with projects that use Symfony `4.x` components.
