### ISSUE TITLE
Ignore files in a directory

### ISSUE THREAD

**Issue by mattalberon** [nunomaduro/collision#135]
I would like to ignore specified directories from the output. 

For example, in Laravel the TestResponse class may be extended to give more assertion methods - but I do not want to view this file in the output.

It looks as if the list in this method would fulfil the requirements:

https://github.com/nunomaduro/collision/blob/1e43bcab2ce79146b9852ca81a25ae2d1d21986b/tests/Unit/WriterTest.php#L126

However, the list is hard-coded:

https://github.com/nunomaduro/collision/blob/fef86518b5bab6373eb282068bfa4ce25bb723d1/src/Adapters/Phpunit/Style.php#L163

Would it be possible to configure the directories which are ignored?

**Comment by nunomaduro** [comment]
Not yet, fell free to add that feature.
