### ISSUE TITLE
PHPUnit logging configuration is not respected when passed to `php artisan test` on Laravel

### ISSUE THREAD

**Issue by lucavallin** [nunomaduro/collision#144]
### Description:

PHPUnit logging configuration is not respected when passed to Laravel's `php artisan test`.

### Steps To Reproduce:

In my `phpunit.xml` I have:

```
<logging>
        <log type="coverage-text" target="php://stdout" showUncoveredFiles="false" showOnlySummary="true" />
    </logging>
```

If I run `phpunit`, at the end I get a coverage report in the shape of:

```
Code Coverage Report Summary:
  Classes: 50.00% (6/12)     
  Methods: 63.64% (14/22)    
  Lines:   58.82% (30/51)    
```

If I run `php artisan test` instead, I only get:

```
Tests:  7 passed
 Time:   3.04s
```

`php artisan test --coverage-text` doesn't work either, even though the default output for the option is to STDOUT.
However, if I run `php artisan test --coverage-text=coverage.txt`, a `coverage.txt` with the information I am expecting is created, but I really need this report in my `stdout` and I am not able to do that.

See my previous issue on Laravel's repo: https://github.com/laravel/framework/issues/33986

**Comment by markjaquith** [comment]
I got bitten by this too. It disregarded my `phpunit.xml` config which tells tests to run on another database, and it wiped out my local dev database with like 16 million rows 😭.

It seems to have been fixed in version `4.2.0`.

`composer require --dev "nunomaduro/collision ^4.2"`

**Comment by mathieutu** [comment]
Actually this is more general. `php artisan test` doesn't care at all about the `phpunit.xml` file!

**Comment by nunomaduro** [comment]
@lucavallin What collision version are you using?

**Comment by SteveEdson** [comment]
Is this broken again, using `"nunomaduro/collision" v5.4.0`? Doesn't respect the coverage reporting options

**Comment by Shizzen83** [comment]
I've also encountered this issue (v5.4.0) on my project :confused: 

`php vendor/bin/phpunit` result:
```
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 00:00.732, Memory: 42.00 MB

OK (2 tests, 2 assertions)

Generating code coverage report in HTML format ... done [00:02.305]
```

`php artisan test` result:
```
  PASS  Tests\Unit\ExampleTest
  ✓ basic test

   PASS  Tests\Feature\ExampleTest
  ✓ basic test

  Tests:  2 passed
  Time:   0.80s
```

The Artisan way ignores my code coverage

`phpunit.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true"
>
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
    </testsuites>
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">./app</directory>
        </include>
        <report>
            <html outputDirectory="public/coverage"/>
        </report>
    </coverage>
    <php>
        <server name="APP_ENV" value="testing"/>
        <server name="BCRYPT_ROUNDS" value="4"/>
        <server name="CACHE_DRIVER" value="array"/>
        <server name="DB_CONNECTION" value="sqlite"/>
        <server name="DB_DATABASE" value=":memory:"/>
        <server name="MAIL_MAILER" value="array"/>
        <server name="QUEUE_CONNECTION" value="sync"/>
        <server name="SESSION_DRIVER" value="array"/>
        <server name="TELESCOPE_ENABLED" value="false"/>
    </php>
</phpunit>
```

**Comment by mxsxs2** [comment]
`--coverage-text` of phpunit is still not printing out the coverage when using `php artisan test --coverage-text` in version 5.11.
The package behaves the same as @Shizzen83 described in his comment. 

@nunomaduro is this desired behavior or do we need to change something to work?
