### ISSUE TITLE
Collision 5.x can be installed in a Laravel 7 app

### ISSUE THREAD

**Issue by michaeldyrynda** [nunomaduro/collision#149]
Unfortunately, this leads to an error when running `php artisan test`

```
Running Collision ^5.0 artisan test command requires Laravel ^8.0.
```

The project dependencies are otherwise met correctly, for dependabot to have marked this as a compatible upgrade.

**Comment by nunomaduro** [comment]
You will need upgrade to PHPUnit 8.
