### ISSUE TITLE
PHP 8 compatibility?

### ISSUE THREAD

**Issue by Synchro** [nunomaduro/collision#151]
I gather that pest 0.31 [supports PHP 8.0-dev](https://github.com/pestphp/pest/blob/v0.3.1/composer.json#L20), however, pest depends on collision, and collision has a dep on PHP `^7.3` and won't install for me:

```
  Problem 1
    - nunomaduro/collision[v5.0.0-BETA1, ..., v5.0.2] require php ^7.3 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - pestphp/pest v0.3.1 requires nunomaduro/collision ^5.0 -> satisfiable by nunomaduro/collision[v5.0.0-BETA1, ..., v5.0.2].
    - Root composer.json requires pestphp/pest ^0.3.1 -> satisfiable by pestphp/pest[v0.3.1].
```

My composer config doesn't depend on any explicit version of collision, just:

```
  "require-dev": {
    "roave/security-advisories": "dev-master",
    "vimeo/psalm": "^3.15",
    "squizlabs/php_codesniffer": "^3.5.6",
    "phpcompatibility/php-compatibility": "^9.3.5",
    "phpunit/phpunit": "^9.3.8",
    "pestphp/pest": "^0.3.1",
    "phpstan/phpstan": "^0.12.42",
    "nunomaduro/phpinsights": "^1.14"
  },
```

I can't see any lurking dev branches of collision – how should I set this up?

**Comment by nunomaduro** [comment]
Can you make a pull request on that? Please also update the GitHub tests files.

**Comment by owenvoke** [comment]
It looks like Collision is already being tested against PHP 8, so I guess we'd just need to update the supported versions in the Composer JSON?

**Comment by Synchro** [comment]
I tracked down what allows it to work for pest – `--ignore-platform-req=php` in the action definition makes composer ignore PHP version mismatches, which I didn't know. That will work fine for me, but I'll make PRs anyway.

**Comment by Synchro** [comment]
OK, that didn't quite work. We can't quite get rid of the PHP platform ignore just yet as other things fail too:

```
  Problem 1
    - Root composer.json requires nunomaduro/mock-final-classes ^1.0 -> satisfiable by nunomaduro/mock-final-classes[v1.0.0].
    - nunomaduro/mock-final-classes v1.0.0 requires php ^7.1 -> your php version (8.0.0-dev) does not satisfy that requirement.

  Problem 2
    - Root composer.json requires laravel/framework ^8.0 -> satisfiable by laravel/framework[8.x-dev].
    - laravel/framework 8.x-dev requires php ^7.3 -> your php version (8.0.0-dev) does not satisfy that requirement.

  Problem 3
    - facade/ignition-contracts[1.0.0, ..., 1.0.1] require php ^7.1 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - Root composer.json requires facade/ignition-contracts ^1.0 -> satisfiable by facade/ignition-contracts[1.0.0, 1.0.1].
```

I will fix and clean up.

**Comment by Synchro** [comment]
I've submitted [a PR that should fix Problem 1](https://github.com/nunomaduro/mock-final-classes/pull/2).
Problem 2 should be fixed now that Laravel 8 has been released
No idea about problem 3!

**Comment by nunomaduro** [comment]
Done.
