### ISSUE TITLE
Why is support for symfony/console < "^5.0" dropped?

### ISSUE THREAD

**Issue by mdeboer** [nunomaduro/collision#155]
I was wondering why support for symfony/console versions older than 5 was dropped once support for version 5 was added? I'm not aware of any immense BC changes that would lead to dropping support for older versions.

I would really like to use pestphp that uses this package with a Symfony 4 project and would be happy to contribute any changes required to get this working with at least symfony/console 4.

**Comment by nunomaduro** [comment]
No plans. I don't use any framework / package with Symfony 4.

**Comment by mdeboer** [comment]
Thanks for closing this issue so quickly _without_ answering my question @nunomaduro. I guess I will figure it out myself and open a PR once I get it working.

**Comment by weitzman** [comment]
I'm also interested in this compatibility, for the [Drush](https://www.drush.org) project (the CLI for Drupal)
