### ISSUE TITLE
Option to hide exception titles

### ISSUE THREAD

**Issue by hotmeteor** [nunomaduro/collision#165]
In the PHPUnit `Style` class, it will set `showTitle` to `false` if it's an instance of a `AssertionFailedError` class:
https://github.com/nunomaduro/collision/blob/68e891f72def020a51ad2c87391ee5a0c226fb0b/src/Adapters/Phpunit/Style.php#L176

It would be great if there was a way to define in a service provider which additional exception titles you'd like to hide, ie. a custom exception from a package.

**Comment by nunomaduro** [comment]
Feel free to pull request an RenderlessTitle pull request. https://github.com/nunomaduro/collision/tree/stable/src/Contracts.
