### ISSUE TITLE
PHP 8 issues

### ISSUE THREAD

**Issue by sefaYavuz** [nunomaduro/collision#167]
When I'm trying to `composer update`:

```
- symfony/console[v5.1.0-BETA1, ..., v5.1.0-RC1] require php ^7.2.5 -> your php version (8.0.0) does not satisfy that requirement.
- Root composer.json requires nunomaduro/collision ^5.0 -> satisfiable by nunomaduro/collision[v5.0.0-BETA1, ..., v5.1.0].
```

Can we use the `symfony/console v5.2.1`?

**Comment by owenvoke** [comment]
Collision requires `^5.0` of Symfony Console, so 5.2.1 will be used if it's available. Is something else requiring 5.1.x? 🤔

**Comment by sefaYavuz** [comment]
I've deleted my vendor folder and rerun the `composer install` command which fixed my problem. So case closed!
