### ISSUE TITLE
error unpexted ')'

### ISSUE THREAD

**Issue by donakhseputa** [nunomaduro/collision#170]
![image](https://user-images.githubusercontent.com/13846150/105389113-0bc92900-5c4a-11eb-880b-3e6974bbdb7e.png)

On path `src/Adapters/Laravel/Commands/TestCommand.php` method `handle` please remove sign `,` before line `))->setTimeout(null);` makes error, because last parameter should not have sign `,`

**Comment by owenvoke** [comment]
What PHP version are you using? This is fine in [PHP 7.3 and later](https://wiki.php.net/rfc/trailing-comma-function-calls) (which is the requirement for Collision 5).

**Comment by donakhseputa** [comment]
ahh, sorry I run laravel artisan with other php version.
