### ISSUE TITLE
Support to Parallel Testing in Lumen

### ISSUE THREAD

**Issue by robertoarruda** [nunomaduro/collision#171]
### Versions:
**Collision** Version: 5.3
**Lumen** Version: 8.2.1
**PHP** Version: 7.4.13

### Description:
The Parallel Test is not supported because the Lumen does not have the class "Illuminate\Foundation\Application"

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/6320754/105998769-bf3b7e80-608b-11eb-9c8f-049ee3cb5111.png)

**Comment by nunomaduro** [comment]
No plans on adding parallel testing on Lumen.

**Comment by mabalashov** [comment]
**Versions:**
**Collision** Version: 5.3
**Lumen** Version: 8.2.3
**PHP** Version: 8.0.2

This issue occurs even while running `php artisan test`, in the non-parallel mode

So, the Collision doesn't work at Lumen at all
But you have a Lumen section in documentation: https://github.com/nunomaduro/collision#lumen-adapter

**Comment by nunomaduro** [comment]
https://github.com/nunomaduro/collision/commit/8e003f0a20adeff692c505beb6ea58e122b1d921

**Comment by nunomaduro** [comment]
Removed the Lumen adapter from the documentation.
