### ISSUE TITLE
Testing environment only set when specifying as an option

### ISSUE THREAD

**Issue by bobbybouwmann** [nunomaduro/collision#191]
Hi all,

I was tinkering around with running `php artisan test` and running `vendor/bin/phpunit`. I found out that they both run a different environment. `phpunit` automatically sets the env to `testing` where `php artisan test` uses the one that is specified in your `.env`, which is `local` by default. Because of this you clear your current database when running `php artisan test`. 

I first looked into the documentation and it told me to create ` .env.testing` file. This file would automatically be used if your env was set to `testing`. This works perfectly for `phpunit` but doesn't seem to work for `php artisan test`. It is still using the `local` envionment. Adding the `--env=testing` option seems to fix this.

https://laravel.com/docs/8.x/testing#the-env-testing-environment-file

It feels unnatural to me that we need to specify this environment, even though we have a `.env.testing` available. I would expect that the env would be set to `testing` if a `.env.testing` file is available when running `php artisan test`. 

Maybe I have misconfigured something or I missed something else. Let me know if you have any other questions to get a better overview of what's going on.

**Comment by nunomaduro** [comment]
What collision version are you using?

**Comment by bobbybouwmann** [comment]
I'm running `v5.6.0`, but also tried `v5.8.0`

**Comment by nunomaduro** [comment]
Bobby, can you create a laravel application, open source it, and send me so I can test it out quickly?

**Comment by bobbybouwmann** [comment]
Mmh, I was testing it out on a new repository and had no issues. Tried it again on my current project and it seems to work as expected again... Could have been cache somehow. 

Anyway, it seems it's just a glitch on my side. Thanks for the support.
