### ISSUE TITLE
More frames in stack trace?

### ISSUE THREAD

**Issue by jasonvarga** [nunomaduro/collision#195]
Is it possible to show more than 2 lines of the stack trace? I'm using the PHPUnit adapter.

![image](https://user-images.githubusercontent.com/105211/140553403-bf7b156c-f0a5-4f07-a88a-71f448fa14e2.png)

(Sorry if this has already been answered)

**Comment by nunomaduro** [comment]
@jasonvarga Yes - use the option `-v` in your console.

**Comment by jasonvarga** [comment]
🤦 Of course! Wonderful, thank you.
