### ISSUE TITLE
Better code highlighting

### ISSUE THREAD

**Issue by felixdorn** [nunomaduro/collision#198]
![image](https://user-images.githubusercontent.com/55788595/142848032-d73936f4-56f0-4ca8-bf26-07ab569fef9b.png)
> Example output using JetbrainsDark Theme.

I've built https://github.com/felixdorn/tin for exactly these kind of tools.

I think it would clean up a lot the complicated `Highlighter` class as well.

The package makes it very easy to customize the output so adding stuff like arrows, line numbers  is very easy. 

LMK if I should submit a PR.

**Comment by nunomaduro** [comment]
Interesting. Can you make a draft PR ,so I can see how it looks like?

**Comment by felixdorn** [comment]
Yes, will do!

**Comment by felixdorn** [comment]
`felixdorn/tin` requires PHP 8 and makes heavy use of the new `match` keyword.

How would we implement that as collision requires ^7.3 and all the solutions I thought about are quite complicated aka not worth the effort.

What do you think? When will collision stop supporting 7.3, 7.4 ?

**Comment by nunomaduro** [comment]
You should target Collision v6, and the branch develop.
