### ISSUE TITLE
Laravel 5.8 issue

### ISSUE THREAD

**Issue by mustafaabduljalil** [nunomaduro/collision#205]
I got this error how can i fix it please i'm using laravel 5.8 

production.ERROR: Class 'JakubOnderka\PhpConsoleColor\ConsoleColor' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'JakubOnderka\\PhpConsoleColor\\ConsoleColor' not found at /home/smssfhati/laravel/vendor/nunomaduro/collision/src/Highlighter.php:47)

Regards

**Comment by nunomaduro** [comment]
Please use the latest version of Collision.
