### ISSUE TITLE
Laravel Adapter: Don't render exception on partial artisan commands

### ISSUE THREAD

**Issue by OwenMelbz** [nunomaduro/collision#21]
Hey, love the package so far :) Very helpful!

I have found one gripe which is annoying, and maybe a very edge case - but if you deem it fixable then I think it's definitely an improvement.

So if you type something like 

`php artisan migrates` instead of `php artisan migrate` it throws a `CommandNotFoundException`

However artisan already handles this and gives you suggestions - the suggestions get a bit battered due to the exception also rendering.

Would it be possible to ignore that exception?

![1st-choice-spares_ _owen_batman](https://user-images.githubusercontent.com/1094740/32663283-61a020ea-c625-11e7-9a7e-0d9c55bd77dc.jpg)

**Comment by nunomaduro** [comment]
Hey! Thanks for using collision!

This is the behaviour of Artisan:

<img width="556" alt="screenshot 2017-11-10 21 22 15" src="https://user-images.githubusercontent.com/5457236/32677100-7c436e06-c65d-11e7-84e5-b716bfbd8fe5.png">

What do you think removing the stack trace of collision only?

**Comment by OwenMelbz** [comment]
Yeah I think that’s cool, just don’t think you need the stack trace or the code snippet around the exception.

Keeping it simple :)

**Comment by nunomaduro** [comment]
The Pull Request https://github.com/nunomaduro/collision/pull/23 is ready and tomorrow I will run some tests. Meanwhile if you wanna to test use this version: "nunomaduro/collision": "dev-hotfix-1.1.9"

**Comment by nunomaduro** [comment]
@OwenMelbz You feature demand got merged. Do you mind of doing a `composer update nunomaduro/collision` and tell me if everything is good?

**Comment by OwenMelbz** [comment]
@nunomaduro Will give it a whirl tomorrow :D

**Comment by nunomaduro** [comment]
This should be good! 😉

**Comment by eleftrik** [comment]
@nunomaduro Thanks for this update, I really appreciated it!

In my opinion, there is another case where exceptions shouldn't be catched by your package: when there are not enough arguments running a command.

For example, if I run `php artisan foo:bar:create` without passing a mandatory argument (let's say "projectname", in this case), I would like to see this output:

```
 [Symfony\Component\Console\Exception\RuntimeException]
  Not enough arguments (missing: "projectname").

```
(with classic background red output)


...instead of 
```

  Symfony\Component\Console\Exception\RuntimeException : Not enough arguments (missing: "project, recipe").

  at /.............../vendor/symfony/console/Input/Input.php: 82
  78:             return !array_key_exists($argument, $givenArguments) && $definition->getArgument($argument)->isRequired();
  79:         });
  80:
```

Is there a way?

Thank you

**Comment by OwenMelbz** [comment]
I wonder if it’s worth making a collision config - which allows you to put an array of exceptions not to render?

**Comment by nunomaduro** [comment]
@OwenMelbz Collision now ignores all exceptions that implement `Symfony\Component\Console\Exception\ExceptionInterface`. I believe this should answer your problem 👍

**Comment by OwenMelbz** [comment]
👍🏼
