### ISSUE TITLE
Configure Phpunit\Style "ignoreFilesIn"

### ISSUE THREAD

**Issue by kbond** [nunomaduro/collision#213]
I know this was rejected in https://github.com/nunomaduro/collision/pull/183 but can I ask this be reconsidered? I have several paths I'd like to exclude to help make the failure output more useful to me. It doesn't make sense to add these to this repo directly (which appears to be the only option right now).

Maybe there could be a different way to configure? `tests/bootstrap.php` maybe?

```php
// tests/bootstrap.php

NunoMaduro\Collision\Adapters\Phpunit\Style::addToErrorIgnore([
    '/vendor\/foo\/bar/',
    '/vendor\/bar\/baz/',
]);
```

**Comment by owenvoke** [comment]
I think this would be better as mentioned as part of a PHP entry method, rather than as part of the `phpunit.xml` 👍🏻 It could be quite useful for things such as private app-specific exclusions.

**Comment by kbond** [comment]
Cool, I'll put together a PR.

**Comment by alexander-schranz** [comment]
I'm asking in which cases we want to show the line from `vendor` directory? So maybe all from `vendor` should be excluded by default? So we always get the line which we are calling.

**Comment by nunomaduro** [comment]
I think is a good idea, yet needs to be something like:

```php
NunoMaduro\Collision::ignoreSomething...
```
