### ISSUE TITLE
symfony/console requirement compatibility with Laravel 9

### ISSUE THREAD

**Issue by Eduardowm** [nunomaduro/collision#217]
Laravel 9.x right now it's requiring [symfony/console](https://packagist.org/packages/symfony/console) 6.0.0 but `nunomaduro/collision` package is asking for at least `symfony/console` 6.0.2, so they are not compatible right now.

The funny thing it's that on Laravel's migration page (8 to 9) it say to use `nunomaduro/collision` 6.1... I'm I doing something wrong?

Thanks!

**Comment by nunomaduro** [comment]
Please ensure your composer json looks like so: https://github.com/laravel/laravel/blob/9.x/composer.json.
