### ISSUE TITLE
facade/ignition-contracts abandoned?

### ISSUE THREAD

**Issue by WalterWoshid** [nunomaduro/collision#221]
This package uses `facade/ignition-contracts` as a dependency and it seems like it is abandoned. Why?

Because [solutions](https://flareapp.io/docs/solutions/adding-custom-solutions) aren't working, [see this issue](https://github.com/spatie/laravel-ignition/issues/70). There is already a [pull request](https://github.com/facade/ignition-contracts/pull/7), but it seems [the package is abandoned](https://github.com/facade/ignition-contracts/pull/7#issuecomment-1047831030)

**Comment by nunomaduro** [comment]
That's fixed.
