### ISSUE TITLE
Printer doesn't respect @testdox annotation

### ISSUE THREAD

**Issue by vaites** [nunomaduro/collision#223]
Working with Laravel tests I found that the `artisan test` command doesn't respect the [TestDox functionality](https://phpunit.readthedocs.io/en/9.5/textui.html#testdox), while PHPUnit does. I think the descriptions should show the `@testdox` value if it has been defined or, at least, allow users to enable it using the `--testdox` flag.

Steps to reproduce:

1. Install Laravel (`composer create-project laravel/laravel example-app 9.x`)
2. Add `@testdox Test description using TestDox` to the comment of the `Tests\Feature\ExampleTest::test_the_application_returns_a_successful_response()` method
3. Run `artisan test`, then `vendor/bin/phpunit --testdox` and compare the test case descriptions

This is the `artisan test` output:

```
PASS  Tests\Unit\ExampleTest
 ✓ that true is true

PASS  Tests\Feature\ExampleTest
 ✓ the application returns a successful response

Tests:  2 passed
Time:   0.22s
```
And this is the `vendor/bin/phpunit --testdox``` output:

```
PHPUnit 9.5.19 #StandWithUkraine

Example (Tests\Unit\Example)
 ✔ That true is true

Example (Tests\Feature\Example)
 ✔ Test description using TestDox

Time: 00:00.215, Memory: 22.00 MB

OK (2 tests, 2 assertions)
```

Digging in the code I found that the method `NunoMaduro\Collision\Adapters\Phpunit\TestCase::makeDescription()` method does almost the same that `PHPUnit\Util\TestDox::NamePrettifier::prettifyTestMethod()`, and in the same class the method `prettifyTestCase()` parses the annotation and use it instead of the _prettyfied_ method name. So, why not use it?. 

Didn't make a pull request because I don't know if this is intentional, and should be discussed before making the changes.

**Comment by vaites** [comment]
I tried only with Laravel, but using the printer _standalone_ will cause the same problem.

**Comment by owenvoke** [comment]
I'd assume this is probably intentional, but not sure. 🤔 Would probably make sense to use the TestDox name if it exists and `--testdox` is used.

**Comment by vaites** [comment]
> I'd assume this is probably intentional, but not sure. 🤔 Would probably make sense to use the TestDox name if it exists and `--testdox` is used.

I also think the best option is to add `--testdox` to the Artisan command. That way the current behaviour is not changed. If you want I can add it and make a PR...

**Comment by vaites** [comment]
After digging into the code I found that there's no need to fix anything. Adding the `--testdox` option to PHPUnit command is enough and as the `artisan test` command uses `argv`, the expected result can be obtained just running `artisan test --testdox`.
