### ISSUE TITLE
Readme clarification regarding inclusion with Laravel

### ISSUE THREAD

**Issue by joelmellon** [nunomaduro/collision#228]
From the readme:
> It's included on Laravel, the most popular free, open-source PHP framework in the world.

and
> As an example, here is how to require Collision on Laravel 6.x:
> `composer require nunomaduro/collision:^3.0 --dev`

If it's "included on Laravel" why does it need to be require'd as well? Can you clarify what "included" means? Supported by Laravel, maybe?

**Comment by owenvoke** [comment]
Yeah, this can probably be removed as it's been included in newer Laravel versions (and added retrospectively to old Laravel versions) for a while. 🤷🏻 Feel free to open a PR, not sure if this was intentionally just to show how to install a specific version. 🤔

**Comment by joelmellon** [comment]
@owenvoke Do you know when Laravel started including it?

**Comment by owenvoke** [comment]
Sorry, I'm not entirely sure about that. 🤷🏻

**Comment by joelmellon** [comment]
It's all good, I was just going to update the readme with which versions would need manual composer installation.
