### ISSUE TITLE
Access Laravel config inside phpunits setUpBeforeClass

### ISSUE THREAD

**Issue by devloberto** [nunomaduro/collision#237]
Calling Laravels `config()` function or the getter `Config::get` inside a `setUpBeforeClass` method that overwrites `\PHPUnit\Framework\TestCase::setUpBeforeClass` leads to the following output:
![image](https://user-images.githubusercontent.com/41804849/199768226-65788667-95f7-4144-8e4f-c415e4b3b1a4.png)

For instance:
```php
public static function setUpBeforeClass(): void
{
    parent::setUpBeforeClass();
    $someConfig = \Illuminate\Support\Facades\Config::get('some.config');
}
```
or
```php
public static function setUpBeforeClass(): void
{
    parent::setUpBeforeClass();
    $someConfig = $bla = config('some.config');
}
```

**Comment by nunomaduro** [comment]
Feel free to make a pull request that addresses that issue.
