### ISSUE TITLE
PhpUnit test running in separate process can have confusing error output

### ISSUE THREAD

**Issue by mortenscheel** [nunomaduro/collision#238]
Let me start by saying that this is kind of a weird corner case, and I am 100% to blame for ending up in this situation. And I don't know if Collision could (or should) display this type of error in a different way to avoid confusion, but I'll post this in case you want to.

Here's a simple test that demonstrates the issue
```php
class ExampleTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp();
        // Simulating a custom trait on the base TestCase printing a message to STDERR
        fwrite(STDERR, "\033[32mEnvironment validated.\033[0m\n");
    }

    /**
     * @runInSeparateProcess
     * @preserveGlobalState disabled
     */
    public function test_mocking_a_hard_dependency()
    {
        // Simulating a test that has to be run in a separate process in
        // order to allow mocking a static method call on a class that might already be loaded.
        $this->assertTrue(true);
    }
}
```

Normally PhpUnit doesn't care if you write to STDERR during tests, but if a test runs in a separate process, it will result in an [exception getting thrown](https://github.com/sebastianbergmann/phpunit/blob/2854bdd8a1e8bd3831ee3622c6f0951684d08490/src/Util/PHP/AbstractPhpProcess.php#L267).

Here's the output of from `php artisan test`:
![image](https://user-images.githubusercontent.com/6514342/203287780-be27ba6b-9cda-4f6c-8265-069e91ed9cc3.png)

Possibly because I'm an idiot, but looking at this output several times, I didn't realize that "Environment validated" _was_ the exception. Especially because it's written in green, and also I'm used to seeing it every time I run my test suite. So in stead I focused on the highlighted code, which doesn't really provide any value in this case.

Here's the output from vanilla PhpUnit:
![image](https://user-images.githubusercontent.com/6514342/203288003-82db8bb1-ad2a-4141-b9a0-8b12d0561fd5.png)

Displayed like this, I instantly realized what the problem was.

**Comment by nunomaduro** [comment]
We don't support the separate process option.
