### ISSUE TITLE
Support composer vendor dir (don't hard code vendor path)

### ISSUE THREAD

**Issue by nunodonato** [nunomaduro/collision#246]
Right now, if a project has the vendor folder in another place, it is not possible to run `php artisan test` as the vendor path is hardcoded.

This was fixed in tinker by checking COMPOSER_VENDOR_DIR in the .env file https://github.com/laravel/tinker/pull/73/files

**Comment by nunomaduro** [comment]
Can you make a pull request that addresses your issue?
