### ISSUE TITLE
Missing test highlighting

### ISSUE THREAD

**Issue by jrd-lewis** [nunomaduro/collision#249]
When upgrading to Laravel 10 today with the recommended dependency upgrade to version ^7.0 of this package, the highlighting of the output was somehow changed. I am running on Windows 11, if it's possible that it's an OS-specific problem.

Previously to updating the package, it looked like this:
![image](https://user-images.githubusercontent.com/17649602/218805066-866401e7-99a7-485c-ad99-1dc05ff29ea1.png)

After the update, it looks like this:
![image](https://user-images.githubusercontent.com/17649602/218804932-9cd7c358-0792-4d85-8704-018415f9774e.png)

**Comment by nunomaduro** [comment]
What happens if you don't use the `--without-tty` option?

**Comment by jrd-lewis** [comment]
Without that option, the highlighting still isn't there. So, the only difference is that it shows the warning about TTY not being supported on Windows.

**Comment by nunomaduro** [comment]
@jrd-lewis Can you try the option `--ansi`, and let me know how it goes?

**Comment by nunomaduro** [comment]
@jrd-lewis Also, can you share your "composer.json"?

**Comment by jrd-lewis** [comment]
> @jrd-lewis Can you try the option `--ansi`, and let me know how it goes?

Interestingly, that does add the highlighting back. I haven't used that option previously.

> @jrd-lewis Also, can you share your "composer.json"?

It's mostly the same as the composer.json from the laravel/laravel repo.

```json{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/fortify": "^1.16",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "spatie/laravel-sluggable": "^3.4.2"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.8",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

**Comment by nunomaduro** [comment]
This is fixed on the latest version of Collision.
