### ISSUE TITLE
Can we remove the dependency on laravel/sanctum ?

### ISSUE THREAD

**Issue by AlexDanault** [nunomaduro/collision#252]
Introduced here:  https://github.com/nunomaduro/collision/commit/eb2cb49b35b6b3bc5f501607d0eb49357af8016b

But I searched the code and I don't see this dependency used in this project.

This dependency bubbles up in projects and adds a migration to create a personal_access_tokens2 table. I'd be okay with the table if I use sanctum, but in some projects I don'T and I don'T want the table.

If this is approved, I can PR the change.

**Comment by owenvoke** [comment]
This is a dev dependency, so shouldn't be required in your application. 👀 These files are also for tests. I think something else is introducing this... 🤔

**Comment by AlexDanault** [comment]
I have my minimum-stability set to "dev" (with prefer-stable = true) because I'm developing packages, that may explain why I end up with the dev dependencies in my project.

I see this package has laravel tests but I'm not seing sanctum used specifically in those tests, it looked like it was added by default and not used (I could be wrong) so that'S why I asked.

**Comment by AlexDanault** [comment]
OMG, I am so dumb. The table was coming from a test package of mine, not from this package.

I'm really sorry for the wasted time !
