### ISSUE TITLE
Print out the results in real-time during the test run with sail

### ISSUE THREAD

**Issue by lucabecchetti** [nunomaduro/collision#258]
I'm using the @nunomaduro  Collision library as a PHPUnit printer for my Dusk tests, but i'm not seeing the results printed out in real-time during the test run. it seems that it waits until all tests have completed before outputting the results.

I use: 

sail test --stop-on-failure and my phpunit.dusk.xml has:

`
  <phpunit backupGlobals="false"
           backupStaticAttributes="false"
           bootstrap="vendor/autoload.php"
           colors="true"
           convertErrorsToExceptions="true"
           convertNoticesToExceptions="true"
           convertWarningsToExceptions="true"
           processIsolation="false"
           stopOnFailure="false"
           printerClass="NunoMaduro\Collision\Adapters\Phpunit\Printer"
           printerFile="./vendor/phpunit/phpunit/src/Util/Log/CollaborativeTestListener.php"
  >
`

**Comment by nunomaduro** [comment]
Can you share a video or gif of what do you mean?
