### ISSUE TITLE
Running `php artisan test` with different option order fails.

### ISSUE THREAD

**Issue by MeesterDev** [nunomaduro/collision#260]
Running `php artisan test --without-tty --profile -v` works fine. Running `php artisan test --profile --without-tty -v` will result in an error.

```
PHPUnit 10.0.11 by Sebastian Bergmann and contributors.

Unknown option "--without-tty"
```

I believe the error is the assumption that the --without-tty option is always passed first, but in reality, the invocations should run the same.

See:
https://github.com/nunomaduro/collision/blob/d9205550494a8e6865ae59eaa3fd0f77f6c916fb/src/Adapters/Laravel/Commands/TestCommand.php#L102

I'm not sure if just this line should be changed or the `phpunitArguments` and `paratestArguments` should filter the `without-tty` option instead. I'll gladly make a PR with some instructions as to which solution is preferable.

**Comment by nunomaduro** [comment]
I am not sure what's the problem here. Can you make a pull request?
