### ISSUE TITLE
Coverage report section is not displayed after upgrading to PHPUnit 10

### ISSUE THREAD

**Issue by leunggamciu** [nunomaduro/collision#263]
It seems that PHPUnit 10 treats empty test cases differently from PHPUnit 9.

```php
use PHPUnit\Framework\TestCase;

class ExampleTestCase extends TestCase
{
}
```

In PHPUnit 9, the result would be

<img width="583" alt="image" src="https://user-images.githubusercontent.com/1306857/223759635-0b906e04-d4cb-4d46-9c33-33fdc5a4d204.png">

In PHPUnit 10

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1306857/223760289-db0937e0-1e8b-41cb-8578-5f79de76c024.png">

And because of the exit code check 

https://github.com/nunomaduro/collision/blob/2b97fed4950cf0ff148c18b853975ec8ea135e90/src/Adapters/Laravel/Commands/TestCommand.php#L140 

If there is accidentally an empty test case in the test suite (in my case :)), and run `php artisan test --coverage`, the final test result appears to have passed, but the coverage report does not show up

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1306857/223763511-2219be43-cdde-445f-97dd-29d2b72caeff.png">

I'm not sure if this is a bug, but it took me quite a few moments to figure out . I was thinking if it's possible to add a section showing the status of the test result.

**Comment by nunomaduro** [comment]
Not idea what's happening here. Sorry!
