### ISSUE TITLE
PHPUnit errors are not shown in test output

### ISSUE THREAD

**Issue by jnoordsij** [nunomaduro/collision#271]
When a test is run and triggers a PHPUnit error, this error is not shown in the output of the `php artisan test` command. This can cause the test run to exit with a non-zero exit code, but no visible issues in the output, which can be confusing to end-users.

An example can be found in https://github.com/jnoordsij/laravel-laravel/tree/test-exit-code:

PHPUnit output, which shows an error
```
$ ./vendor/bin/phpunit tests/Unit/ExampleTest.php || echo $?
PHPUnit 10.1.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.5
Configuration: R:\upstream\laravel\laravel\phpunit.xml

.                                                                   1 / 1 (100%)

Time: 00:00.005, Memory: 10.00 MB

There was 1 PHPUnit error:

1) Tests\Unit\ExampleTest::test_with_provider
The data provider specified for Tests\Unit\ExampleTest::test_with_provider is invalid
Empty data set provided by data provider

R:\upstream\laravel\laravel\tests\Unit\ExampleTest.php:24

OK (1 test, 1 assertion)
2
```

Artisan output, which shows no error, but does exit with non-zero code
```
$ php artisan test tests/Unit/ExampleTest.php || echo $?

   PASS  Tests\Unit\ExampleTest
  ✓ that true is true

  Tests:    1 passed (1 assertions)
  Duration: 0.10s

2
```

I think some sort of handling of https://github.com/sebastianbergmann/phpunit/blob/main/src/Event/Events/Test/Issue/PhpunitErrorTriggered.php should occur within https://github.com/nunomaduro/collision/blob/v7.x/src/Adapters/Phpunit/Printers/DefaultPrinter.php to solve this issue, but I'm not exactly sure on the exact workings.

**Comment by coogle** [comment]
Thank god for this bug post, I thought I was going crazy because I was trying to set up a CI/CD pipeline and it kept returning `2` and I couldn't figure out why! At least now I have a path forward by trying this running `phpunit` directly and seeing what error messages are being lost here.

After spending about 5 hours on this yesterday I can tell you: This is a seriously painful bug!
