### ISSUE TITLE
PhpUnit 10.3 introduced some breaking changes

### ISSUE THREAD

**Issue by alexey-m-ukolov** [nunomaduro/collision#281]
Sebastian Bergmann [implemented some breaking changes](https://github.com/sebastianbergmann/phpunit/commit/20d613e3eea463756714d53c45ba3b80c46404fe) in the `PHPUnit\TestRunner\TestResult\TestResult` (which marked as internal). Notably, some public methods that Collision relied on where removed (`TestResult::numberOfTests()` for example). See https://github.com/sebastianbergmann/phpunit/issues/5460 for additional context.

**Comment by regnerisch** [comment]
Confirmed, I'm getting `Call to undefined method PHPUnit\TestRunner\TestResult\TestResult::numberOfTests()` on `php artisan test tests/Feature/UserTest.php`

**Comment by nunomaduro** [comment]
Fixed [v7.8.0](https://github.com/nunomaduro/collision/releases/tag/v7.8.0).
