### ISSUE TITLE
Is it possible to add the progress % to the PHPUnit printer?

### ISSUE THREAD

**Issue by robiningelbrecht** [nunomaduro/collision#285]
By default PHPUnit adds a progress percentage indication behind each line:
![image](https://github.com/nunomaduro/collision/assets/203894/126e9d70-c434-496f-9afd-ca1a631c26ed)

Is it possible to add this to Collision compact output as well? Maybe as an option?

**Comment by lucabecchetti** [comment]
any news?

**Comment by nunomaduro** [comment]
You can use `--compact`.

**Comment by owenvoke** [comment]
@nunomaduro, I think the point here is that the percentage / progress isn't shown in `--compact`. 🤔 It only has the dots.

**Comment by robiningelbrecht** [comment]
Exactly. As far as I know, there are no percentages displayed. Not sure why the issue got closed?

**Comment by robiningelbrecht** [comment]
If this is a "won't do", I'm perfectly fine with that, but just closing without feedback is kinda weird...
