### ISSUE TITLE
No documented way to use only the PHPUnit (10) printer

### ISSUE THREAD

**Issue by Bilge** [nunomaduro/collision#297]
If one wishes to only use the PHPUnit 10 printer, it is unclear how to do this, since there is no extension to bootstrap.

**Comment by robiningelbrecht** [comment]
@Bilge You can use this extension that uses Collision: https://github.com/robiningelbrecht/phpunit-pretty-print

**Comment by Bilge** [comment]
OK, but that seems like it does a lot more than just enable Collision, what with the Chuck Norris quotes and other unnecessary guff.

In reality, isn't this the single and only line that is actually needed to enable the printer?

https://github.com/robiningelbrecht/phpunit-pretty-print/blob/5d42dbf9d92a6299d3307d59b1a67c9eba22e065/src/PhpUnitExtension.php#L35

**Comment by robiningelbrecht** [comment]
@Bilge Everything is disabled by default.
And yes that line is the bare minimum you need to run Collision, but I think you need to run it in an PHPUnit extension to make it work.

**Comment by Bilge** [comment]
I imagine you could just run it in the bootstrap file, no?

**Comment by robiningelbrecht** [comment]
@Bilge That might an option as well indeed, never tried this before.
Since PHPUnit 10 I tend to work with the "extensions and events" it provides...

**Comment by Bilge** [comment]
It seems this is wrong. There appears to be some autoload trick going on that causes `EnsurePrinterIsRegisteredSubscriber::register();` to be called automatically (see [`Autoload.php`](https://github.com/nunomaduro/collision/blob/0225cf94fc9aaf645bbc42b5fc838aace025e0e3/src/Adapters/Phpunit/Autoload.php#L11)). Therefore, the only thing required to enable the printer is to ensure `COLLISION_PRINTER` environment variable is set (to anything, including nothing).

However, when I do this, although the printer is _enabled_, the output is messed up as it is now a mish-mash of Collision and PHPUnit output (it outputs the dots (`...`) between tests). Moreover, the text colour is dark grey which is difficult to read; I don't know if this is intended or not, but it wasn't the case with v6.

![image](https://github.com/nunomaduro/collision/assets/470626/d1ba474c-e700-40b0-8d37-5e7f1e64fdbf)

If I use your extension, the dots go away, but the text is still illegible. Presumably the dots are fixed by instructing PHPUnit to omit its own test output as here: https://github.com/robiningelbrecht/phpunit-pretty-print/blob/5d42dbf9d92a6299d3307d59b1a67c9eba22e065/src/PhpUnitExtension.php#L24C18-L24C39 What is strange about this is that there does not appear to be any equivalent call in Collision itself. But how do we even know Collision v7 even works with PHPUnit, considering [its own test suite](https://github.com/nunomaduro/collision/actions/runs/7216156497/job/19661827812#step:6:16) does not appear to activate the printer at all? 


---
Aside, the text colour in v6 was also grey, but a lot lighter.

![image](https://github.com/nunomaduro/collision/assets/470626/31dc9d76-038c-45da-af28-31baaa52c806)

**Comment by robiningelbrecht** [comment]
@Bilge yeah indeed, you need to disable PHPUnit10's output, forgot about that, sorry.

> But how do we even know Collision v7 even works with PHPUnit

Because the extension you are referring to has it's own test suite and proves it works?

**Comment by srtfisher** [comment]
Previously non-Laravel projects had the option to use `printerClass` and enjoy collision. Now it seems that those outside of Laravel (or those who run `vendor/bin/phpunit` directly rather than through a wrapper function) can't use collision as easily.

**Comment by Bilge** [comment]
Yeah but why wouldn't everyone be using Laravel, the best static framework where everything is static and what even is concurrency safety anyway?

**Comment by BafS** [comment]
I got the exact same issue, the readme doesn't help. I agree that legibility is not great and I don't get why we need https://github.com/robiningelbrecht/phpunit-pretty-print if this package says it's PHPUnit compatible.

**Comment by robiningelbrecht** [comment]
> I got the exact same issue, the readme doesn't help. I agree that legibility is not great and I don't get why we need https://github.com/robiningelbrecht/phpunit-pretty-print if this package says it's PHPUnit compatible.

Well, tbh it's PHPUnit compatible... it just takes some work 😎

**Comment by Bilge** [comment]
☝🏻🤓  TEKNICHALLY
