### ISSUE TITLE
[7.x] Misleading error message for incompatible PHPUnit version

### ISSUE THREAD

**Issue by mbabker** [nunomaduro/collision#300]
Renovate opened PRs today to update some apps to use PHPUnit 11.  In these PRs, `artisan test` fails with this message:

"Running Collision 7.x artisan test command requires at least PHPUnit 10.x."

This is a bit misleading as the code is explicitly checking for exactly version 10 and not at least version 10.

(I realize this might be a won't fix at this point but figured I'd log it since the error message threw me off until I looked at the code)

**Comment by nunomaduro** [comment]
Fixed here; https://github.com/laravel/framework/pull/49957.
