### ISSUE TITLE
Any way to make collision respect phpunit --stop-on-error?

### ISSUE THREAD

**Issue by alexciarlillo** [nunomaduro/collision#37]
I think there was a closed issue related to this. I use this feature pretty often when running the complete test suite so I can walk away, get some coffee, come back and see what a mess I made during my refactor. Just wondering if it is possible to modify the PHPUnit listener to respect this flag.

**Comment by nunomaduro** [comment]
@alexciarlillo If you are using collision, collision will always makes your tests stop on failure. What do you mean exactly?

**Comment by alexciarlillo** [comment]
PHPUnit has 2 command line flags: --stop-on-error and --stop-on-failure. I would like it if collision did not stop the entire test suite if I have passed the --stop-on-error flag. In that case I only want the tests to stop if an error is encountered, not a failure.

**Comment by nunomaduro** [comment]
@alexciarlillo This is the problem that @driesvints have specified on the issue https://github.com/nunomaduro/collision/issues/27.

@alexciarlillo The development release `v1.1.21` should fixed that. Do you mind running some tests locally? Please perform `composer require nunomaduro/collision:dev-hotfix-1.1.21 --dev` and run some tests. 👍

**Comment by nunomaduro** [comment]
@alexciarlillo Ping.

**Comment by alexciarlillo** [comment]
Just got around to testing (long day). Works like a charm! Thanks

**Comment by nunomaduro** [comment]
@alexciarlillo Ok. I will release this version! 👌

**Comment by nunomaduro** [comment]
@alexciarlillo You can now update your composer to a stable version of Collision!

**Comment by baldarn** [comment]
Hi,
it seems that on laravel 7.x this issues happens again.

see https://github.com/laravel/framework/issues/31914

**Comment by nunomaduro** [comment]
@baldarn What do you mean?

**Comment by baldarn** [comment]
running
```
php artisan test
```
with stopOnFailure="false" in the phpunit.xml file stop the execution, but it shouldn't

can this be a bug of collision?

**Comment by nunomaduro** [comment]
It's on purpose. We don't support that option yet

**Comment by pildit** [comment]
May I ask you why you don't support it ?
