### ISSUE TITLE
Support PHPUnit 7

### ISSUE THREAD

**Issue by sebastiaanluca** [nunomaduro/collision#41]
Just a head's up that PHPUnit 7 has changed the format of `TestListener::addError`, which is incompatible with the current version of this package. See https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-7.0.md#changed.

>PHP Fatal error:  Declaration of NunoMaduro\Collision\Adapters\Phpunit\Listener::addError(PHPUnit\Framework\Test $test, Exception $e, $time) must be compatible with PHPUnit\Framework\TestListener::addError(PHPUnit\Framework\Test $test, Throwable $t, float $time): void in /vagrant/vendor/nunomaduro/collision/src/Adapters/Phpunit/Listener.php on line 33

**Comment by nunomaduro** [comment]
@sebastiaanluca I will check that this weekend. Thanks!

**Comment by ianrodrigues** [comment]
You can check PR #42

**Comment by nunomaduro** [comment]
@ianrodrigues This PR is already merged on Collision v2. Should come out before the end of this month.

**Comment by nunomaduro** [comment]
@ianrodrigues Fell free to use it already: `composer require nunomaduro/dev-release-2.0.0`.

**Comment by nunomaduro** [comment]
@ianrodrigues Collision v2 is out. Enjoy! 🎉
