### ISSUE TITLE
PHPUnit: Support assert diffs

### ISSUE THREAD

**Issue by luispabon** [nunomaduro/collision#44]
I made an example repo:

https://github.com/luispabon/collision-diff

Run tests without: `vendor/bin/phpunit`
Run tests with: `vendor/bin/phpunit -c ./phpunit-with-collision.xml`

I can see that collision is adding it's pretty output at the very end, but it's not showing the diff in the json string asserts on the test - that's still at the original phpunit output. In this particular case (typical for an end-to-end api functional test), you need to scroll all the way up to find the diffs.

This would be the case I imagine with any other asserts that produce diffs.

Suggestion: add the assert diff beneath the current Collision output, with colour coding.

Here's a screenshot - the terminal on the right shows  what it could potentially be displayed beneath the current Collision output:

![image](https://user-images.githubusercontent.com/6388823/36541791-f5d7e754-17d6-11e8-8400-a76bc1e47303.png)

The output from the left is simply the original diff from phpunit in a file, displayed by `pygmentize`.

**Comment by nunomaduro** [comment]
@luispabon Thanks for reporting this issue. I truly believe that Collision can improve the phpunit adapter. Give me few days to think about a roadmap on it. 👍

**Comment by nunomaduro** [comment]
@luispabon Sorry for not be able to help you yet. Do you think you will be able to work on a PR on this?

**Comment by nunomaduro** [comment]
Done on the `next` branch.

**Comment by luispabon** [comment]
Thank you very much :+1:
