### ISSUE TITLE
Support for Symfony Console Applications

### ISSUE THREAD

**Issue by sunel** [nunomaduro/collision#49]
Great package 👏 , as the title says, any plan for symfony console?

**Comment by nunomaduro** [comment]
@sunel The integration with Symfony 4 is coming real soon.

**Comment by nunomaduro** [comment]
@sunel Just created https://github.com/nunomaduro/collision-adapter-symfony. Enjoy!

**Comment by sunel** [comment]
@nunomaduro 

The collision-adapter-symfony is for symfony application using bundle.

But for console like the below, how can i integrate this 

https://symfony.com/doc/current/components/console.html

**Comment by nunomaduro** [comment]
@sunel Just add this code `(new \NunoMaduro\Collision\Provider)->register();` on your cli file.

**Comment by trevorpan** [comment]
Hello @nunomaduro, 

I've searched for ` (new \NunoMaduro\Collision\Provider)->register();` all over the web; there are many sites that have the installation steps but they reference the main docs page - which does not have a file noted. 

> Just add this code (new \NunoMaduro\Collision\Provider)->register(); on your cli file.

May I please know, what is the cli file you are referencing? So - in a Laravel 7 app where would this file be found?

Thank you much,
Trevor
