### ISSUE TITLE
PhpUnit 8 support

### ISSUE THREAD

**Issue by alphametric** [nunomaduro/collision#59]
The listener needs to be modified to support PHPUnit 8:

`if (class_exists(\PHPUnit\Runner\Version::class) && substr(\PHPUnit\Runner\Version::id(), 0, 2) === '7.') {`

to

`if (class_exists(\PHPUnit\Runner\Version::class) && substr(\PHPUnit\Runner\Version::id(), 0, 2) === '8.') {`

**Comment by nunomaduro** [comment]
Can you do a pull request ? Ideally can you also add a test into this.

**Comment by alphametric** [comment]
I wouldn’t worry about it just yet. As I’ve discovered, Laravel will need to make quite a few changes to support v8.

**Comment by nunomaduro** [comment]
What do you think about marking this as first good issue ?

**Comment by alphametric** [comment]
It would have been, yes, but I've since made a PR for it #60
