### ISSUE TITLE
Writer not respecting --no-ansi when displaying the editor

### ISSUE THREAD

**Issue by claudiofreitas** [nunomaduro/collision#63]
When calling a Laravel Command passing `--no-ansi` flag, the method `renderEditor(Frame $frame)` in `Writer` class send the contents to the highlighter and outputs with color regardless of the flag.

Expected: When an Exception occurs inside a Command that has been called with `--no-ansi`, display everything in the terminal without any color.

Current: Everything but the editor is correctly displayed. The editor part has color.

**Comment by fitztrev** [comment]
Confirmed. I'll just add the steps I did to recreate:

Create a console command in `routes/console.php`:
```php
Artisan::command('foo', function () {
    $this->comment('comment');

    throw new Exception('error');
});
```

Then run the command with the `--no-ansi` flag but still see color:
```shell
$ php artisan foo --no-ansi
```

**Comment by nunomaduro** [comment]
Thanks @claudiofreitas @fitztrev. Are you guys able to work on a fix to this?

**Comment by fitztrev** [comment]
I can't.

**Comment by claudiofreitas** [comment]
Sorry for the delay (didn't notice the notification).

No problem!
I can try, but maybe in 1 week.

**Comment by nunomaduro** [comment]
@claudiofreitas Can you still work on this? The next version is on the `next` branch.

**Comment by claudiofreitas** [comment]
@nunomaduro Hi Nuno! I wanted to be of some help, but I won't lie to myself (and others here) again. I don't think I will be able to work on this right now. I tried last time but got blocked and felt embarrassed to ask for help. I'm sorry.

**Comment by nunomaduro** [comment]
No worries. It's fine.

**Comment by nunomaduro** [comment]
No plans on fixing this.
