### ISSUE TITLE
feat: add ignition features on collision

### ISSUE THREAD

**Issue by webong** [nunomaduro/collision#67]
Hey @nunomaduro,

 Would it be possible to for the collision package to integrate with Flare, so one can share the public link with anybody they'll like to show their error with?

**Comment by nunomaduro** [comment]
It's a great idea! I already have something locally. Waiting from @caneco the design.

**Comment by caneco** [comment]
Here it is the current proposals for the _next collision_ screen.

**Error with custom solutions**

![preview-collission-next](https://user-images.githubusercontent.com/502041/64347386-c15ef200-cfeb-11e9-856c-2af1c9245c35.png)

**Error with "runnable" solutions**

![preview-collission-next-2](https://user-images.githubusercontent.com/502041/64347394-c328b580-cfeb-11e9-9edc-20e401bbc864.png)

**Comment by MrRio** [comment]
Can you interactively run a fixer? 👀

**Comment by riasvdv** [comment]
Ignition can show multiple possible (runnable) solutions, can this be handled in Collision as well or does it just show the first one?

**Comment by MrRio** [comment]
Failing interactive Y/n prompt, could do `--fix`

**Comment by webong** [comment]
I find the Y/N prompt more viable...  `--no-fix` could then be appended if user doesn't want a  solution prompt.

**Comment by dillingham** [comment]
if you do solutions, maybe make it like vendor:publish:

[1] Solution One
[2] Solution Two
[3] None

Which solution?

**Comment by nunomaduro** [comment]
Done on the `next` branch.
