### ISSUE TITLE
How to use in lumen?

### ISSUE THREAD

**Issue by ingen2** [nunomaduro/collision#69]
How to use in lumen?
What is console command (instead of ` php laravel-zero inspiring`)?

**Comment by nunomaduro** [comment]
Checkout the docs: https://github.com/nunomaduro/collision#lumen-adapter.

**Comment by ingen2** [comment]
Ok, but My problem is `php laravel-zero inspiring` command 
error: Could not open input file: laravel-zero

**Comment by nunomaduro** [comment]
That's an example using: https://laravel-zero.com

**Comment by ingen2** [comment]
where is example using lumen???
