### ISSUE TITLE
Not work with symfony/console 5

### ISSUE THREAD

**Issue by daom89** [nunomaduro/collision#71]

**Comment by ianrodrigues** [comment]
@daom89 Any more info?

**Comment by nunomaduro** [comment]
@daom89 can you be more explicit?

**Comment by daom89** [comment]
Good morning, I'm sorry for my English, yesterday I didn't have time to explain myself. The [symfony/console](https://github.com/symfony/console/releases/tag/v5.0.0) package in version 5 solves a number of problems when displaying characters in console. I need to update this component in my laravel project, but when I try to do this composer throws the following error:

**Problem 1**
    - nunomaduro/collision v3.0.1 requires symfony/console ~2.8|~3.3|~4.0 -> satisfiable by symfony/console[2.8.x-dev, 3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
    - nunomaduro/collision v3.0.0 requires symfony/console ~2.8|~3.3|~4.0 -> satisfiable by symfony/console[2.8.x-dev, 3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
    - nunomaduro/collision v3.0.1 requires symfony/console ~2.8|~3.3|~4.0 -> satisfiable by symfony/console[2.8.x-dev, 3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 3.3.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 3.4.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 4.0.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 4.1.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 4.2.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 4.3.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 4.4.x-dev].
    - Can only install one of: symfony/console[v5.0.0, 2.8.x-dev].
    - Installation request for symfony/console 5.0.0 -> satisfiable by symfony/console[v5.0.0].
    - Installation request for nunomaduro/collision ^3.0 -> satisfiable by nunomaduro/collision[v3.0.0, v3.0.1].

**Comment by ianrodrigues** [comment]
@nunomaduro was it solved at #72 ?

**Comment by daom89** [comment]
Yes

**Comment by nunomaduro** [comment]
It's not tagged yet. It's on the works.
