### ISSUE TITLE
Support symfony/console ^5.0

### ISSUE THREAD

**Issue by mbadolato** [nunomaduro/collision#80]
Can you release a new tag with a change for allowing for `symfony/console ~2.8|~3.3|~4.0|~5.0` in composer.json?

**Comment by nunomaduro** [comment]
It's under works: https://github.com/nunomaduro/collision/tree/next.

You can already try it out using `composer require nunomaduro/collision:"^4.0" --dev`. But is not stable yet.

**Comment by tobeycodes** [comment]
FYI @nunomaduro I can't upgrade to v4 because of this constraint 

`laravel/framework              v6.13.1  requires  symfony/console (^4.3.4)`
