### ISSUE TITLE
latest version does not seem to work with Laravel 6.x

### ISSUE THREAD

**Issue by Nothing-Works** [nunomaduro/collision#83]
Hi I am aware of this issue #70 but for some reason, I still can not use the latest version for laravel 6.x

Here are the steps to reproduce,

1. `laravel new test` (`Laravel Framework 6.12.0`)

2. `composer require nunomaduro/collision --dev`
![Capture](https://user-images.githubusercontent.com/18606648/73026930-4bbeca00-3e97-11ea-9847-5d90f07e09e1.PNG)
Am I doing somethin wrong? if anyone could help that will be good. Thanks

**Comment by nunomaduro** [comment]
It's on propose. This new version is exclusively for Laravel ^7
