### ISSUE TITLE
On testing exceptions Collision should not render exceptions

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/collision#9]
In Laravel, we may want to test if an exception is throw correctly. Given the following routes/web.php:

```
Route::get('/', function () {
    throw new Exception("This is an exception");
});
```

And the following test:

```
$response = $this->get('/');
$response->assertStatus(500);
```

Our application exception handler should not render an exception.

**Comment by bobbybouwmann** [comment]
I think you need some kind of middleware to that, or tweak your exception handler. Not sure if this should be package specific. Just my two cents!

If I have some time left today I will look into this a bit more ;)

**Comment by nunomaduro** [comment]
@bobbybouwmann Thanks fo you two cents! I may dive into this issue this weekend 😎

**Comment by san4io** [comment]
I think it also shouldn't react in tests to default exceptions like: Validation, Unauthorized, Unauthenticated.

I'm writing test  and expect to get 401, of course it passes, but dunno if your listener should catch such exceptions, or maybe it would be great to have ignoredExceptions configuration: 

```
$response = $this->json('GET', '/api/v1/claims');

$response->assertStatus(401);
```

Illuminate\Auth\AuthenticationException : Unauthenticated.

  at /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php: 66
  62:                 return $this->auth->shouldUse($guard);
  63:             }
  64:         }
  65: 
  66:         throw new AuthenticationException('Unauthenticated.', $guards);
  67:     }
  68: }
  69: 

All in all, awesome package. :)

**Comment by nunomaduro** [comment]
@san4io Thanks for the feedback and for your suggestion!

I will definitely find something this issue. I just didn't have 5 mins minutes to look into to it. I may check tomorrow!

**Comment by nunomaduro** [comment]
@san4io @bobbybouwmann We all agree that, on `testing env` we only want to render APPLICATION exceptions (via collision) when the status code is 500 right?

**Comment by nunomaduro** [comment]
@bobbybouwmann @san4io I was thinking about using the method `$this->shouldReport($e)` to understand if collision should render the exception on `testing` environment. 

Like committed on this hot-fix branch: https://github.com/nunomaduro/collision/commit/ae9f452e64cb8e4b3a5c237068a967cb7125b057

Like that, all Laravel Internal exceptions are ignored on `testing` env by Collision. What do you guys think? 😊

**Comment by nunomaduro** [comment]
The version `v1.1.6` should have this problem fixed.

**Comment by bobbybouwmann** [comment]
This looks pretty good to me! Great job on this :D
