### ISSUE TITLE
TestCommand not respecting output colors

### ISSUE THREAD

**Issue by jrd-lewis** [nunomaduro/collision#90]
OS: Windows 10 Build 18363.657
Windows Terminal (beta): 0.9.433.0
Laravel Version: 7.0-dev

How to reproduce:
- Run `php artisan test`
- The output doesn't include the highlighting from this package's printer class.
- Note: when I tried using `PHPUnit\TextUI\ResultPrinter` in the printer parameter for the artisan command, the colors aren't respected either.
- With the printer class from this package specified in `phpunit.xml`, the colors are respected when running via `vendor\bin\phpunit`

**Comment by nunomaduro** [comment]
Can you quick use the Laravel Dusk test command to see if you have the same problems?

**Comment by nunomaduro** [comment]
Can you send me the screenshot of the output?

**Comment by jrd-lewis** [comment]
This is the output from Dusk:
![Dusk-Test](https://user-images.githubusercontent.com/17649602/75394782-ece9d780-58be-11ea-961e-6905e03ec3e6.png)

**Comment by nunomaduro** [comment]
Also no colours?

**Comment by jrd-lewis** [comment]
This is the output from `php artisan test`:

![Artisan-Test](https://user-images.githubusercontent.com/17649602/75394575-6a611800-58be-11ea-835b-b683fcec44f4.png)

And, this is the output from `vendor\bin\phpunit`:
![PHPUnit-Test](https://user-images.githubusercontent.com/17649602/75394073-608ae500-58bd-11ea-86bb-b2186dc8d4c0.png)

**Comment by nunomaduro** [comment]
You can pass the option `--without-tty`?

**Comment by jrd-lewis** [comment]
I can pass that option, and I updated the screenshot in my last comment to reflect that.

**Comment by nunomaduro** [comment]
@jrd-lewis Humm. I will check this tomorrow.

**Comment by owenvoke** [comment]
Interesting, I get this with both PowerShell 5 and PowerShell Core, but with CMD the colours show as expected (all using Windows Terminal). 🤔

If I run PowerShell 5/Core through ANSICON (using `ansicon powershell`), it displays the colours as expected.

<details>
<summary>Preview output image</summary>

![Output preview](https://image.prntscr.com/image/sYgp08oZTd_GpNeSujh2jg.png)

</details>

**Comment by nunomaduro** [comment]
You still face this issue?

**Comment by owenvoke** [comment]
I still do when I use Windows, but since I've been working from home I luckily don't have to use Windows. 🥳

**Comment by jrd-lewis** [comment]
I'm also still experiencing this on Windows.

**Comment by nunomaduro** [comment]
@owenvoke @jrd-lewis do you think there is a solution for this? If yes, can you try to develop a fix?

**Comment by owenvoke** [comment]
I'll have a look, but I haven't been able to find much. 😕

**Comment by m50** [comment]
I am having a similar issue:

I have a composer script ("test") that runs `php ./vendor/bin/phpunit --colors=always`, and with Collision, it outputs no color, but if I run `composer test -- --testdox` it displays color as expected.

(I had to blank out a lot of stuff, because this is in a closed-source product, but you should be able to tell regardless the color issues)

<img width="795" alt="Screen Shot 2020-05-19 at 9 58 42 AM" src="https://user-images.githubusercontent.com/3577147/82342818-b3090880-99b7-11ea-8192-46de447e9123.png">

As you notice `RUN` is not colored, but the checkmarks for testdox are.

**Comment by nunomaduro** [comment]
@m50 Can you try collision 5?

**Comment by jrd-lewis** [comment]
@nunomaduro I just tried the collision 5 beta 1 release and it is showing the colors properly for me on Windows.

**Comment by m50** [comment]
I'm sorry, swamped right now, and not able to test yet. Hopefully this weekend I can validate as well.

**Comment by nunomaduro** [comment]
@m50 Seems to be fixed in Collision 5 beta 1. Let me know if it works for you too.
