### ISSUE TITLE
Adding collision to a package laravel package

### ISSUE THREAD

**Issue by roni-estein** [nunomaduro/collision#97]
I have a simple package that I'm adding tests to for the first time, I enjoy working with collision in laravel so I was hoping I could also add it to a laravel package.

So far I've installed collision:

```
composer require nunomaduro/collision --dev
```

I've edited the I also have phpunit 9.0.1, I actually meant to install 8.5.1 so I could run tests from inside phpstorm.
if I run tests from the command line now, I end up with the following:
<img width="466" alt="Screen Shot 2020-03-05 at 3 50 54 PM" src="https://user-images.githubusercontent.com/8517475/76028960-365aa800-5ef9-11ea-89a6-eec20e953451.png">

Once I add collision to phpunit.xml I get the following error:

<img width="435" alt="Screen Shot 2020-03-05 at 3 53 03 PM" src="https://user-images.githubusercontent.com/8517475/76029095-70c44500-5ef9-11ea-93ce-15c65b4a07e1.png">

I've attempted to register collision in the boot and boot methods of the service provider, however neither seem to remove this. Can you let me how a package should be configured to allow collision?

Thanks

**Comment by matijakovacevic** [comment]
Yes, it should be fixed in the docs @nunomaduro 

It's `NunoMaduro\Collision\Adapters\Phpunit\Listener` instead of
`NunoMaduro\Collision\Adapters\Phpunit\Printer`

**Comment by nunomaduro** [comment]
You are using a old version of collision.

**Comment by roni-estein** [comment]
Got it sorted, sorry forgot to close this.
