### ISSUE TITLE
Stop on failure gets ignored

### ISSUE THREAD

**Issue by ShawnCZek** [nunomaduro/collision#98]
## Environment

Collision version: v4.1.3
Laravel version: v7.0.6
PHPUnit version: v8.5.1

## Description

Running the command `php artisan test` stops on the first failure even when all `stopOn` settings are set to `false`.

This seems to be an issue with the [`Style::writeError()`](https://github.com/nunomaduro/collision/blob/f7505183009bebd7636f3efded2b177a8827b2a3/src/Adapters/Phpunit/Style.php#L203) method which throws `exit(1)` at the end. Removing that line makes tests continue, however, the output behaves weirdly then as the status of the class is printed twice.

## How to reproduce

- Make two tests where one fails (must be declared as first) and the second one is successful
- Run `php artisan test`

**Comment by nunomaduro** [comment]
That's an intentional behaviour. `The Artisan test runner provides more information regarding the test that is currently running and will automatically stop on the first test failure:`. https://laravel.com/docs/7.x/testing#artisan-test-runner

**Comment by tobyryuk** [comment]
Is there a specific reason for this? We have quite a big codebase with tests and are running them quite frequently when refactoring to see how much changes break.

**Comment by zgosalvez** [comment]
@tobyryuk I suggest just using phpunit directly for that use case.
