### ISSUE TITLE
Less verbose printer

### ISSUE THREAD

**Issue by robsontenorio** [nunomaduro/collision#99]
It would be nice to have a less verbose option. Just that "dots", but keep  the "beauty error handler".

**Comment by nunomaduro** [comment]
Ideas on this?

**Comment by robsontenorio** [comment]
Just for clarifying.

Allow to use this output, but keep the collision error hanlder.

![image](https://user-images.githubusercontent.com/118955/81307178-c383bf80-9056-11ea-9ae7-f2c05987b644.png)

**Comment by nunomaduro** [comment]
I think we do better than that.

**Comment by robsontenorio** [comment]
Sometimes you just want a overview of tests (with "dots" report), but also a nice error handler output.

Once collision is a "printer" i really don't know if it would be possible to configure through params. But if so, i am willing to submit a PR.

**Comment by nunomaduro** [comment]
@AlexMartinFR is working on that.

**Comment by rl-zembrowski** [comment]
@mikeerickson does a great job with [phpunit-pretty-result-printer](https://github.com/mikeerickson/phpunit-pretty-result-printer). The output is very minimalistic.

The only thing missing there is an integration with Collision. It would be a perfect match to get phpunit-pretty-result-printer with your collision error handler, Nuno.

Any chances to get back the Listener which was removed in v4.1?

**Comment by zembrowski** [comment]
@mikeerickson does a great job with [phpunit-pretty-result-printer](https://github.com/mikeerickson/phpunit-pretty-result-printer). The output is very minimalistic.

The only thing missing there is an integration with Collision. It would be a perfect match to get phpunit-pretty-result-printer with your collision error handler, Nuno.

Any chances to get back the Listener which was removed in v4.1?

**Comment by jaggy** [comment]
Hi there! I just wanted to show interest in this issue as well.

Using `php artisan test` seems to be a bit slower (35s) than using phpunit's default printer (16s). I'm not sure if it's related with the printer but it's the only connecting thread I see.

**Comment by mikeerickson** [comment]
@zembrowski @jaggy @robsontenorio keep your eyes pealed for an upcoming release of printer which will have something similar to previous listener integrated with phpunit-pretty-result-printer

**Comment by mikeerickson** [comment]
@AlexMartinFR Is this something that is still on your radar, or have you ditched the plans?  If this is still no your radar, that would be fantastic.

**Comment by nunomaduro** [comment]
@mikeerickson I will probably tackle this myself before PEST v1, and before Laravel 9.

**Comment by alexmartinfr** [comment]
Great new Nuno 👍 

I've hit roadblocks when I tried to implement it properly, and haven't had a chance to try again yet.
Would it help if I shared what I tried and what I was stuck on?

**Comment by mikeerickson** [comment]
@nunomaduro was this implemented or did you decide to drop it?
